### ISSUE TITLE
Cannot use on Windows 11 - nothing opens

### ISSUE THREAD

**Issue by oopiicaa** [iprodanovbg/homeassistant-desktop#11]
Hi.

I have a Huawei Matebook E tablet with Windows 11 Home x64 (vesion 22H2, build 22632.891). CPU is Core i3-1110G4.

I have downloaded Home-Assistant-Desktop-v1.5.2-win-x64.exe and installed it, but nothing happens/opens up. I can see the icon in the tray, but nothing happens if I click it (left or right click). I can see processes running in Task Manager (4 of them). No error messages appear. If I kill the processes and start the program again, nothing changes. I have also tried running it as an admin and still no success.

I have also tried with 32-bit version (Home-Assistant-Desktop-v1.5.2-win.exe) and the issue remains the same.

Rebooting the PC doesn't help.

Any help would be appreciated.

**Comment by oopiicaa** [comment]
Thank you, that was indeed the issue.

**Comment by thezedt** [comment]
Hi,

I can confirm this issue as well. Running an older Windows 10 1809, but perhaps it may be the custom DPI scaling (mine is 115%) that matters more than the version.

**Comment by vespexx** [comment]
As mentioned here https://github.com/iprodanovbg/homeassistant-desktop/issues/1 the temporary solution is 
> disabling Windows scaling, launching it again, setting the app to use a detached Window and then turning scaling back on.

**Comment by thezedt** [comment]
I already used the workaround, sorry for not mentioning that.
I commented only to point out that perhaps it's related to custom scaling, since it appears to happen inconsistently and on different versions of Windows (11 and an ancient 10).
