### ISSUE TITLE
[Featrue request] Output in fullscreen to specified monitor

### ISSUE THREAD

**Issue by DjordjeMandic** [iprodanovbg/homeassistant-desktop#13]
I have multi monitor setup and it would be nice to implement feature to render it on specified monitor in full screen or windowed borderless mode. (currently full screen mode works only on main monitor but taskbar is visible).

I would like to have it output in fullscreen mode to another monitor like a video game with taskbar hidden. (Windowed borderless is my preference)

**Comment by iprodanovbg** [comment]
This is possible when you open the app in detach mode and place it on your target monitor, then you can switch to full screen mode
