### ISSUE TITLE
Cannot click on "SUBMIT" button

### ISSUE THREAD

**Issue by littlerain14** [iprodanovbg/homeassistant-desktop#19]
Hi @iprodanovbg can you check this issues.
I cannot click on SUBMIT button also.

Thanks

<img width="311" alt="Screenshot 2023-02-17 060835" src="https://user-images.githubusercontent.com/38150596/219508678-b5c59b45-74b5-4cc4-bc03-e48f1a9d86bc.png">

**Comment by iprodanovbg** [comment]
Hello,

Can you check if your url is correct and if the url is accessible from your browser because when I test it it is fine with my HA IP
![ezgif-1-a805441941](https://user-images.githubusercontent.com/12864841/219771533-60a2dd10-f55e-45f3-9054-82489984b7a5.gif)

**Comment by littlerain14** [comment]
Thanks for responding,

I don't think my URL is incorrect.  I can access my home assistant by internal URL (HTTP://) and external URL (https://) by chrome browser normally.
I'm using Win11 Pro 64 bits.

Do you have any other suggestions?

Thank in advance

**Comment by rucanunes** [comment]
Same here!

**Comment by iprodanovbg** [comment]
Can you open your HA in your browser and add `/auth/providers` at the end and tell me what response you get on that page

e.g. `http://192.168.31.99:8123/auth/providers`

**Comment by littlerain14** [comment]
Here is the response
 
<img width="406" alt="Screenshot 2023-02-22 205752" src="https://user-images.githubusercontent.com/38150596/220641809-8bacef01-8e88-42dd-bae0-af9c3351f8cc.png">

**Comment by iprodanovbg** [comment]
You should enable the default login method for your home assistant
https://www.home-assistant.io/docs/authentication/providers/#home-assistant-auth-provider

**Comment by littlerain14** [comment]
Thanks, @iprodanovbg.

I try to reconfigure the login method as you recommended, and the home assistant desktop app is working perfectly now.

thank you again :) 

@rucanunes, try this setting:

```
homeassistant:
  auth_providers:
    - type: homeassistant

```
