### ISSUE TITLE
Feature Request: Permanently set Default Dashboard

### ISSUE THREAD

**Issue by LutzFassl** [iprodanovbg/homeassistant-desktop#34]
Hello! I like the Home Assistant Desktop a lot, thanks! :-)

I only have one feature request. I want to use it permanently with a certain dashboard that I created specifically for Desktop.
Would it be possible to add a feature that allows the following:

Everytime Home Assistant Desktop starts up (as usually on Windows Login), it should go to the Dashboard that I can define (somewhere).

Thanks for considering it! BR, Lutz

**Comment by numanair** [comment]
You can just use HA's built-in ability to set a default dashboard per-device, no?

**Comment by LutzFassl** [comment]
**Per Device?** This sounds like what I am looking for. How would I do this?

Since I know that we can have a default dashboard **per user**, you helped me to think about this workaround: I create a new dummy user and set the desired dashboard as default dashboard for this user. Then log in with this user on my home assistant desktop. I will have to check if there are no negative side effects to that workaround.

**Comment by LutzFassl** [comment]
I found the setting "Set as default **on this device**" now in the normal "Dashboards" Settings Menu of Home Assistant. Thank you - really cool! This can be closed.
