### ISSUE TITLE
Define Homepage/Default view

### ISSUE THREAD

**Issue by LennardPlay** [iprodanovbg/homeassistant-desktop#4]
So I have a lovelace view with multiple tabs for the multiple rooms.
It would be great to be able to set a homepage, so that it opens the office view by default. (The room my pc is located in)
Sadly a lovelace specific URL is not accepted by the program.

**Comment by iprodanovbg** [comment]
Hello,

There is a new version that now allows entering URLs for different dashboards.
For now, you can only add new URLs and an option to edit existing instances will be added in a future update

**Comment by Coysh** [comment]
@iprodanovbg - This is great, but what if I want a URL that doesn't start with /lovelace or /energy? I want a custom dashboard to be the starting URL
