### ISSUE TITLE
[v1.5.2] Weird/wrong/no interpretation of CS styles

### ISSUE THREAD

**Issue by bcutter** [iprodanovbg/homeassistant-desktop#7]
After updating from v1.5.1 to v1.5.2 formerly perfectly nice buttons are now shown different which breaks the UI in many places. Few random examples:

![grafik](https://user-images.githubusercontent.com/13799156/202033258-2c949097-bd00-4f4d-9552-0e5db668e726.png)

![grafik](https://user-images.githubusercontent.com/13799156/202033362-e93d1cb8-91e9-4c76-ab15-1189f6206e15.png)

Likely does not respect this CSS inside all `custom:restriction-card` elements:
```
            card_mod:
              style:
                .: |
                  ha-card {
                    aspect-ratio: 1/1
                  }
```

Probably related to `Temporary revert electron version to fix random crashes` in https://github.com/iprodanovbg/homeassistant-desktop/releases/tag/v1.5.2

I have no idea what electron version now runs this app (maybe a pretty old one?), but well, it broke things.

Why can't we switch back to the electron version used in v1.5.1 and try fix the app crash bug instead?
We now avoided to fix that bug by switching electron version - which introduced few new bugs...

**Comment by iprodanovbg** [comment]
Hello,

In this version of electron, "aspect-ratio" is not yet implemented, so if it is custom code, I can suggest you to use flex with `align-items: stretch;`.

> Why can't we switch back to the electron version used in v1.5.1 and try fix the app crash bug instead?
We now avoided to fix that bug by switching electron version - which introduced few new bugs...

I still can't find a solution to crash issue, so I decided to revert the changes. You can disable automatic updates and install an older version until this problem is fixed.

**Comment by bcutter** [comment]
> I still can't find a solution to crash issue, so I decided to revert the changes

Did you meanwhile investigate the crash issues of the newer version?

I still think downgrading the core component because of a crashing issue - which results in the downgraded version creating several other issues like #6 and #7/this one - is not a good decision.

Going back using horses because cars are bad for the environment is not a solution either, isn't it 😄

**Comment by iprodanovbg** [comment]
Sorry for the delay, there is a new version that will fix this issue

**Comment by bcutter** [comment]
> Sorry for the delay, there is a new version that will fix this issue

I will test it asap (in 2 to 3 days) and report back.

**Comment by bcutter** [comment]
v1.5.3 fixed this for me (quick check), even I don't see what in 1.5.3 fixed it as the release notes don't mention anything bout that.
