### ISSUE TITLE
AppImage crashes under Linux

### ISSUE THREAD

**Issue by chris0z** [iprodanovbg/homeassistant-desktop#8]
Here is the output:

09:12:26.186 › homeassistant-desktop started
09:12:26.189 › Platform: linux x64
09:12:26.369 › Checking for update
09:12:26.370 › Initialized main window
09:12:26.489 › Initialized Tray menu
09:12:26.502 › Initialized availability check
[21264:1116/091227.282662:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
[1]    21264 trace trap (core dumped)  ./Home-Assistant-Desktop-v1.5.2-linux-x86_64.AppImage

If i run it with  --no-sandbox its working fine

**Comment by Julusian** [comment]
I'm seeing this too on Ubuntu 22.04.1. 
Running it through gdb doesnt produce a useful stacktrace

**Comment by iprodanovbg** [comment]
This issue is fixed in last update
