### ISSUE TITLE
Cannot click on "SUBMIT"....

### ISSUE THREAD

**Issue by rucanunes** [iprodanovbg/homeassistant-desktop#9]
I can see two instances of HA (local and external).
If i choose one or the other the "Submit" button stays grey...

**Comment by iprodanovbg** [comment]
Hello,

Can you share your URLs so I can test them.

**Comment by littlerain14** [comment]
@iprodanovbg can you check this issues. 

I cannot click on SUBMIT button also.

<img width="311" alt="Screenshot 2023-02-17 060835" src="https://user-images.githubusercontent.com/38150596/219508539-dfd98e57-2353-4d8a-bda5-cac3ebc43e3a.png">
